# Site settings
title: Efrain Antonio Granado Alfaro
email: efraingranadoalfaro@gmail.com
url: https://egranadoa.github.io/
description: "Desarrollador Python | Odoo 16-18"
keywords: "python, desarrollador, odoo"
skills: "Desarrollo de Software con Python | Desarrollo de Módulos Odoo 16 - 18"
meta_author: Granado Efrain

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: "061452" #80B3FF 8AA7FF
  primary-rgb: "6,20,82" #"128,179,255"
  secondary: 6781F4 #FD6E8A 0030BD
  secondary-dark: 6781F4 #A2122F

# Footer settings
footer:
  copyright: Efrain Granado Alfaro
  location: Caracas, Dtto. Capital, Venezuela
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/egranadoa
  - title: linkedin
    url: https://www.linkedin.com/in/efrain-granado-alfaro-4000b9209/

# Postal address (add as many lines as necessary)
address:
  - line: San Martin, Caracas
  - line: Distrito Capital, Venezuela. ZP - 1020 

# Credits content
# credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
